version: '2.0'
# This is only an example that deploys the UDP packet forwarder and helium-gateway-rs at the same time
# Not a stack file
services:

  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:latest
    container_name: udp-packet-forwarder
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      MODEL: "RAK5146"
      CONCENTRATOR: "SX1303"
      SERVER_HOST: "127.0.0.1"
      SERVER_PORT: "1680"
      BAND: "us_902_928"

  helium-gateway-rs:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: sheng2216/helium:latest
#      args:
#        ARCH: aarch64
    container_name: helium-gateway-rs
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /etc/helium_gateway:/etc/helium_gateway/
    command:
      - /bin/bash
      - /app/start.sh
    environment:
      version: "latest"
      platform: "raspi_64"
      region: "US915"
    depends_on:
      - udp-packet-forwarder
